name: build ygopic-best

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'

    - name: Init
      run: |
        npm ci
    
    - name: Build package
      run: |
        npm pack
        mv *.tgz vue3-scss-starry-sky
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: vue3-scss-starry-sky.tgz
        retention-days: 1
        path: ./vue3-scss-starry-sky.tgz

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build

      - name: Create release-latest
        run: |
          cd build
          gh release delete release-latest --cleanup-tag -y || true
          gh release create release-latest $(find . -type f) \
            --target "$GITHUB_SHA" \
            --title "release-latest" \
            --notes "Latest build for ${{ github.ref_name }}" \
            --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
