name: build ygopic-best

on:
  push:
    tags:
      - 'publish*'
    
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'
        registry-url: 'https://registry.npmjs.org/'

    - name: Init
      run: |
        npm ci

    - name: Publish
      run: npm publish --//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}